'use client';
import { useState, useEffect, useRef } from 'react';
import { CheckCircle2, Loader2, ShieldAlert } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { signInWithCustomToken } from 'firebase/auth';
import { auth } from '@/lib/firebase';

export default function InlinePhoneVerifier({ 
  phone, 
  onChange, 
  onVerificationComplete, 
  recaptchaId = 'default' 
}) {
  const [otp, setOtp] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState(false);
  const [otpSent, setOtpSent] = useState(false);
  const [timer, setTimer] = useState(60);
  const [canResend, setCanResend] = useState(false);

  // States to hold stateless HMAC parameters
  const [otpHash, setOtpHash] = useState('');
  const [otpExpiry, setOtpExpiry] = useState('');

  const [touched, setTouched] = useState(false);
  const [validationError, setValidationError] = useState('');
  const timerRef = useRef(null);

  // Validate phone number input and return standard error text
  const validatePhoneInput = (val) => {
    if (!val) return '';
    if (!/^[6-9]/.test(val)) {
      return 'Indian mobile numbers must start with 6, 7, 8, or 9.';
    }
    if (val.length < 10) {
      return `Mobile number must be exactly 10 digits. (${val.length}/10 entered)`;
    }
    return '';
  };

  // Check if phone number is exactly 10 digits and starts with 6-9
  const isIndianMobile = (p) => {
    const cleaned = p ? p.replace(/\D/g, '') : '';
    return cleaned.length === 10 && /^[6-9]/.test(cleaned);
  };
  const isTenDigits = isIndianMobile(phone);

  useEffect(() => {
    // Reset state if phone number changes from 10 digits
    if (!isTenDigits) {
      setOtpSent(false);
      setSuccess(false);
      setError('');
      onVerificationComplete(false);
      stopTimer();
    }
  }, [phone, isTenDigits]);

  useEffect(() => {
    if (otpSent && timer > 0) {
      timerRef.current = setTimeout(() => setTimer(prev => prev - 1), 1000);
    } else if (otpSent && timer === 0) {
      setCanResend(true);
    }
    return () => stopTimer();
  }, [otpSent, timer]);

  const stopTimer = () => {
    if (timerRef.current) {
      clearTimeout(timerRef.current);
    }
  };

  const handleSendOTP = async (e) => {
    if (e) e.preventDefault();
    if (!isTenDigits) return;

    setLoading(true);
    setError('');
    
    const isResend = otpSent;
    if (!isResend) {
      setOtpSent(false);
    }

    try {
      const response = await fetch('/api/otp/send', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          mobile: phone,
          channel: 'sms',
        }),
      });

      const data = await response.json();

      if (!response.ok || !data.success) {
        throw new Error(data.message || 'Failed to send verification code. Please try again.');
      }

      setOtpHash(data.hash);
      setOtpExpiry(data.expiry);
      setOtpSent(true);
      setTimer(60);
      setCanResend(false);
      setOtp(''); // Clear the previous OTP input box on resend

      // Print debug OTP in console when in development environment
    

    } catch (err) {
      console.error("Send OTP error:", err);
      setError(err.message || 'Failed to send verification code. Please try again.');
      if (isResend) {
        setCanResend(true);
      }
    } finally {
      setLoading(false);
    }
  };

  const handleVerifyOTP = async (e) => {
    if (e) e.preventDefault();
    if (!otp || otp.length !== 6) {
      setError('Please enter a 6-digit verification code.');
      return;
    }

    setLoading(true);
    setError('');

    try {
      const response = await fetch('/api/otp/verify', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          mobile: phone,
          otp: otp,
          hash: otpHash,
          expiry: otpExpiry,
        }),
      });

      const data = await response.json();

      if (!response.ok || !data.success) {
        throw new Error(data.message || 'Invalid OTP code. Please check and try again.');
      }
      
      // Programmatically sign user in using Custom Token generated by our secure server
      if (data.customToken && auth) {
        try {
          await signInWithCustomToken(auth, data.customToken);
          console.log("Authenticated successfully with Firebase Auth using Custom Token!");
        } catch (authErr) {
          console.error("Firebase custom token auth failed on client:", authErr);
        }
      }

      setSuccess(true);
      setOtpSent(false);
      onVerificationComplete(true);
      stopTimer();
    } catch (err) {
      console.error("Confirm OTP error:", err);
      setError(err.message || 'Invalid OTP code. Please check and try again.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-3 w-full">
      <div className="relative flex items-center gap-2">
        <div className="relative flex-1">
          <Input 
            type="tel"
            required
            placeholder="Mobile Number" 
            value={phone}
            onChange={(e) => {
              const val = e.target.value.replace(/\D/g, '').slice(0, 10);
              onChange(val);
              
              if (touched || val.length >= 10 || (val.length > 0 && !/^[6-9]/.test(val))) {
                setValidationError(validatePhoneInput(val));
              } else {
                setValidationError('');
              }
            }}
            onBlur={() => {
              setTouched(true);
              setValidationError(validatePhoneInput(phone));
            }}
            disabled={success || loading}
            className={`h-12 bg-gray-50 border-gray-200 focus:bg-white transition-all rounded-xl ${success ? 'pr-10 border-green-500 bg-green-50/20' : ''}`}
          />
          {success && (
            <span className="absolute right-3 top-1/2 -translate-y-1/2 text-green-600">
              <CheckCircle2 size={20} />
            </span>
          )}
        </div>

        {isTenDigits && !success && !otpSent && (
          <Button 
            type="button"
            onClick={handleSendOTP}
            disabled={loading}
            className="h-12 px-5 bg-hitm-navy hover:bg-hitm-red text-white text-xs font-bold uppercase tracking-wider rounded-xl shadow-md shrink-0 active:scale-95 transition-all"
          >
            {loading ? <Loader2 className="animate-spin w-4 h-4" /> : 'Verify'}
          </Button>
        )}
      </div>

      {!success && (
        <div className="flex justify-between items-center text-[11px] px-1 text-gray-500 mt-1 select-none">
          {validationError ? (
            <span className="text-red-500 font-semibold flex items-center gap-1">
              <ShieldAlert size={12} className="shrink-0" /> {validationError}
            </span>
          ) : (
            <span></span>
          )}
          <span className={`${phone && phone.length === 10 ? 'text-green-600 font-bold' : 'text-gray-400 font-medium'}`}>
            {phone ? phone.length : 0}/10 digits
          </span>
        </div>
      )}

      {otpSent && (
        <div className="bg-gray-50 border border-gray-100 p-4 rounded-2xl space-y-3 animate-in slide-in-from-top duration-300 shadow-inner">
          <p className="text-xs text-gray-500 text-center font-medium">
            We have sent an SMS verification code to your phone number.
          </p>
          <div className="flex gap-2">
            <Input 
              type="text"
              maxLength={6}
              placeholder="Enter 6-Digit OTP"
              value={otp}
              onChange={(e) => setOtp(e.target.value.replace(/\D/g, ''))}
              disabled={loading}
              className="h-10 text-center text-sm font-bold tracking-[0.2em] bg-white border-gray-200 rounded-xl"
            />
            <Button
              type="button"
              onClick={handleVerifyOTP}
              disabled={loading || otp.length !== 6}
              className="h-10 px-4 bg-green-600 hover:bg-green-700 text-white text-xs font-bold rounded-xl shadow-md shrink-0 transition-colors"
            >
              {loading ? <Loader2 className="animate-spin w-4 h-4" /> : 'Confirm'}
            </Button>
          </div>

          <div className="flex justify-between items-center px-1 text-[11px]">
            {error ? (
              <span className="text-red-500 font-semibold flex items-center gap-1 animate-pulse">
                <ShieldAlert size={12} /> {error}
              </span>
            ) : (
              <span></span>
            )}
            {canResend ? (
              <button 
                type="button" 
                onClick={handleSendOTP} 
                className="text-hitm-navy hover:text-hitm-red font-bold hover:underline"
              >
                Resend OTP
              </button>
            ) : (
              <span className="text-gray-400 font-medium">Resend in {timer}s</span>
            )}
          </div>
        </div>
      )}

      {error && !otpSent && (
        <p className="text-red-500 text-xs font-bold bg-red-50 p-2.5 rounded-xl border border-red-100 animate-fade-in flex items-center gap-1.5 mt-1">
          <ShieldAlert size={14} className="shrink-0" /> {error}
        </p>
      )}
    </div>
  );
}
